config/routes.rb
Rails.application.routes.draw do
  devise_for :users
  root to: 'babies#index'
  resources :babies, only:[:index, :new, :create, :show]
  resources :babies do
    resources :records, only: [:index, :new, :create]
  end
  resources :users do
    resources :records, only: [:index, :new, :create]
  end
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  primary_abstract_class
end

app/models/baby.rb
class Baby < ApplicationRecord
  has_many :records
  has_one_attached :image
end

app/models/record.rb
class Record < ApplicationRecord
  belongs_to :baby
  belongs_to :user
end

app/models/user.rb
class User < ApplicationRecord
  has_many :records
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  before_action :configure_permitted_parameters, if: :devise_controller?

  private
  def configure_permitted_parameters
    devise_parameter_sanitizer.permit(:sign_up, keys: [:nickname])
  end
end

app/controllers/babies_controller.rb
class BabiesController < ApplicationController
  before_action :move_to_index, except: [:index]

  def index
    @babies = Baby.all
  end

  def new
    @baby = Baby.new
  end

  def create
    @baby = Baby.new(baby_params)

    if @baby.save
      redirect_to babies_path, notice: '赤ちゃんが正常に追加されました。'
    else
      render :index
    end
  end

  def show
    @baby = Baby.find(params[:id])
  end

  private

  def baby_params
    params.require(:baby).permit(:name, :gender, :birth_year, :birth_month, :birth_day, :image)
  end

  def move_to_index
    unless user_signed_in?
      redirect_to action: :index
    end
  end
end

app/controllers/records_controller.rb
class RecordsController < ApplicationController
  before_action :move_to_index
  before_action :find_baby, only: [:index, :new, :create]

  def new
    @record = Record.new
  end

  def index
    @records = Record.where(baby_id: params[:baby_id])
  end

  def create
    @record = Record.new(record_params)

    if @record.save
      redirect_to baby_path(@baby), notice: '記録が追加されました'
    else
      render :new
    end
  end

  private

  def find_baby
    @baby = Baby.find(params[:baby_id])
  end

  def record_params
    params.require(:record).permit(:milk, :oshikko, :unchi, :body_temperature, :memo).merge(baby_id: @baby.id, user_id: current_user.id)
  end

  def move_to_index
    unless user_signed_in?
      redirect_to babies_path
    end
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/babies_helper.rb
module BabiesHelper
end

app/helpers/records_helper.rb
module RecordsHelper
end

app/views/actions/new.html.erb
<h1>新しい記録</h1>

<%= form_with(model: @action, url: baby_actions_path(@baby), method: :post) do |form| %>
  <div class="field">
    <%= form.label :milk, "ミルクの量" %><br>
    <%= form.select :milk, (0..200).step(10), { prompt: '- - - -' }, class: 'milk' %>cc
  </div><br>

  <div class="field">
    <%= form.label :omutsu, "おむつ交換（複数選択可能）" %><br>
    <%= form.check_box :omutsu, { multiple: true }, 'おしっこ', false %> おしっこ
    <%= form.check_box :omutsu, { multiple: true }, 'うんち', false %> うんち
    <%= form.check_box :omutsu, { multiple: true }, 'げり', false %> げり
  </div><br>

  <div class="field">
    <%= form.label :body_temperature, "体温" %><br>
    <%= form.text_field :body_temperature, size: 10, class: 'temperature' %>度
  </div><br>

  <div class="field">
    <%= form.label :memo, "メモ" %><br>
    <%= form.text_area :memo, rows: 3, cols: 30, class: 'memo' %>
  </div><br>

  <div class="actions">
    <%= form.submit "保存", class: "btn btn-primary" %>
  </div>
<% end %>

app/views/babies/index.html.erb
<!DOCTYPE html>
<html lang="ja">
<head>
  <meta charset="UTF-8">
  <meta name="viewport" content="width=device-width, initial-scale=1.0">
  <title>すくすく</title>
  <style>
    body {
      display: flex;
      flex-direction: column;
      align-items: center;
      justify-content: center;
      height: 100vh;
      margin: 0;
    }

    h1 {
      text-align: center;
      font-size: 80px;
      margin: 0 auto 50px;
    }

    .container {
      display: flex;
      align-items: flex-start;
    }

    #image-container {
      margin-right: 50px;
    }

    ul {
      list-style-type: none;
      padding: 0;
      margin-top: 10;
    }

    ul li {
      margin-bottom: 20px;
    }

    .new-baby-link {
      display: block;
      margin-top: 140px;
    }

    .header__bar {
      display: flex;
      justify-content: flex-end;
      width: 100%;
      padding: 0 10px;
      box-sizing: border-box;
    }

    .devises {
      display: flex;
    }

    .devises a {
      margin-left: 10px;
      padding: 0 16px;
      text-decoration: none;
      color: #fff;
      background-color: #4CAF50;
      border-radius: 5px;
      transition: background-color 0.3s;
    }

    .devises a:hover {
      background-color: #45a049;
    }
  </style>
</head>
<body>
  <div class="header__bar row">
    <% if user_signed_in? %>
      <div class="devises">
        <%= link_to "ログアウト", destroy_user_session_path, data: { turbo_method: :delete } %>
      </div>
    <% else %>
      <div class="devises">
        <%= link_to "ログイン", new_user_session_path, class: "post" %>
        <%= link_to "新規登録", new_user_registration_path, class: "post" %>
      </div>
    <% end %>
  </div>

  <h1>す く す く</h1>

  <div class="container">
    <div id="image-container">
      <%= image_tag 'publicdomainq-0006718ljo.jpeg', style: 'width: 300px; height: auto;' %>
    </div>

    <ul>
      <% @babies.each do |baby| %>
        <li>
          <%= link_to baby.name, baby_path(baby), style: "text-decoration: none;" %>
        </li>
      <% end %>
      <%= link_to "新しい赤ちゃん", new_baby_path, class: "btn-success new-baby-link" %>
    </ul>
  </div>

</body>
</html>

app/views/babies/new.html.erb
<style>
  .large-radio {
    transform: scale(1.5);
    margin-right: 10px;
  }
  body {
    padding-left: 38%;
  }
  .eggandchick {
    position: absolute;
    top: 55%;
    left:55%;
  }
</style>

<h1>新しい赤ちゃん</h1>

<%= form_with(model: @baby, url: babies_path, method: :post) do |form| %>
  <div class="field">
    <%= form.label :お名前 %><br>
    <%= form.text_field :name, class: 'name' %>
  </div><br>

  <div class="field">
  <%= form.label :性別 %><br>
  <%= form.radio_button :gender, '男の子', class: 'large-radio' %> 男の子
  <%= form.radio_button :gender, '女の子', class: 'large-radio' %> 女の子
  </div><br>

  <div class="field">
    <%= form.label :生年月日 %><br>
    <%= form.select :birth_year, (Date.current.year - 10..Date.current.year).to_a.reverse, { prompt: '- - - - - -' }, class: 'year' %>年
    <%= form.select :birth_month, 1..12, { prompt: '- - -' }, class: 'month' %>月
    <%= form.select :birth_day, 1..31, { prompt: '- - -' }, class: 'day' %>日
  </div><br>

  <div class="field">
    <%= form.label :画像 %><br>
    <%= form.file_field :image %>
  </div><br>

  <div class="actions">
    <%= form.submit "追加", class: "btn" %>
  </div>

<% end %>

<div class="eggandchick">
  <%= image_tag 'eggandchick.jpeg', style: 'width: 250px; height: auto;' %>
</div>

app/views/babies/show.html.erb
<style>
  body {
    display: flex;
    min-height: 100vh;
    flex-direction: column;
    align-items: center;
    justify-content: center;
    margin: 0;
  }

  .container {
    text-align: center;
  }

  .buttons {
    margin-top: 20px;
    display: flex;
  }

  .common-button {
    background-color: #93E6B4;
    color: #000; /* 黒色 */
    border: none;
    padding: 15px 0; /* 垂直方向のパディングは変更しない */
    font-size: 30px;
    border-radius: 30px; /* 適切な楕円形にするために高さの半分の値 */
    margin-right: 20px; /* ボタン間の横の間隔 */
    width: 200px; /* ボタンの横幅 */
    white-space: nowrap; /* テキストが折り返されないようにする */
  }
</style>

<div class="container">
  <h1><%= @baby.name %></h1>

  <% if @baby.image.present? %>
    <%= image_tag @baby.image, style: 'width: 320px; height: auto;' %>
  <% else %>
    <p>選択した画像がここに表示されます。</p>
  <% end %>

  <div class="buttons">
    <%= button_to "記録する", new_baby_record_path(@baby), method: :get, class: "common-button" %>
    <br>
    <%= button_to "記録を見る", baby_records_path(@baby), method: :get, class: "common-button" %>
  </div>

</div>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Sukusuku</title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag "application", "data-turbo-track": "reload" %>
    <%= javascript_importmap_tags %>
  </head>

  <body>
    <%= yield %>
  </body>
</html>

app/views/records/index.html.erb
<style>
  table {
    border-collapse: collapse;
    width: 100%;
    margin-bottom: 20px;
  }

  th, td {
    border: 1px solid #ddd;
    padding: 8px;
    text-align: center;
  }

  th {
    background-color: #f2f2f2;
  }

  .record-title {
    display: inline-block;
    margin-top: 0;
  }

  .record-image {
    float: right;
    margin-left: 10px;
  }

  .chicks {
    position: absolute;
    top: 5%;
    left:78%;
  }
</style>

<h1 class="record-title"><%= @baby.name %>の記録</h1>
<div class="chicks">
  <%= image_tag 'chicks-removebg-preview (3).png', style: 'width: 300px; height: auto;' %>
</div>

<table class="table">
  <thead>
    <tr>
      <th scope="col">時刻</th>
      <th scope="col">担当</th>
      <th scope="col">ミルク(cc)</th>
      <th scope="col">おしっこ</th>
      <th scope="col">うんち</th>
      <th scope="col">体温(度)</th>
      <th scope="col">メモ</th>
    </tr>
  </thead>
  <tbody>
    <% @records.each do |record| %>
      <tr>
        <td><%= record.created_at.strftime("%m/%d %H:%M") %></td>
        <td><%= record.user.nickname %></td>
        <td><%= record.milk %></td>
        <td><%= record.oshikko ? "●" : "" %></td>
        <td><%= record.unchi ? "●" : "" %></td>
        <td><%= record.body_temperature %></td>
        <td><%= record.memo %></td>
      </tr>
    <% end %>
  </tbody>
</table><br>

<%= link_to "トップに戻る", babies_path, class: "btn btn-primary" %>

app/views/records/new.html.erb
<style>
  body {
    padding-left: 40%;
  }
</style> 
 
 <h1>新しい記録</h1>

<%= form_with(model: @record, url: baby_records_path(@baby), method: :post) do |form| %>
  <div class="field">
    <%= form.label :milk, "ミルクの量" %><br>
    <%= form.select :milk, (0..200).step(10), { prompt: '- - - -' }, class: 'milk' %>cc
  </div><br>

  おむつ交換（複数選択可）<br>
  <div class="field" style="display: inline-block;">
    <%= form.check_box :oshikko %>
    <%= form.label :oshikko, "おしっこ" %>
  </div>

  <div class="field" style="display: inline-block;">
    <%= form.check_box :unchi %>
    <%= form.label :unchi, "うんち" %>
  </div><br><br>

  <div class="field">
    <%= form.label :body_temperature, "体温" %><br>
    <%= form.text_field :body_temperature, size: 10, class: 'temperature' %>度
  </div><br>

  <div class="field">
    <%= form.label :memo, "メモ" %><br>
    <%= form.text_area :memo, rows: 3, cols: 30, class: 'memo' %>
  </div><br>

  <div class="actions">
    <%= form.submit "保存", class: "btn btn-primary" %>
  </div>
<% end %>